"""Minimal MCP client to verify the Review Board server end-to-end over the
real Streamable HTTP protocol (JSON-RPC initialize → tools/list → tools/call).

Runs inside WSL against http://localhost:8765/mcp. Not part of the product —
a verification harness. Delete after confirming. Usage: python3 test_client.py
"""
import json
import urllib.request

URL = "http://localhost:8765/mcp"
_req_id = 0


def call(method: str, params: dict | None = None, sid: str | None = None) -> dict:
    """Send one JSON-RPC request over HTTP POST. Streamable HTTP returns either
    JSON or an SSE stream; for tool calls the server returns plain JSON here."""
    global _req_id
    _req_id += 1
    payload = {"jsonrpc": "2.0", "id": _req_id, "method": method}
    if params is not None:
        payload["params"] = params
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
    }
    if sid:
        headers["Mcp-Session-Id"] = sid
    data = json.dumps(payload).encode()
    req = urllib.request.Request(URL, data=data, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=10) as resp:
        sid = resp.headers.get("Mcp-Session-Id", sid)
        body = resp.read().decode()
        # tolerate SSE-wrapped or plain JSON
        if body.startswith("event:") or body.startswith("data:"):
            for line in body.splitlines():
                if line.startswith("data:"):
                    body = line[5:].strip()
                    break
        return json.loads(body), sid


def main() -> None:
    print("→ initialize")
    res, sid = call(
        "initialize",
        {
            "protocolVersion": "2025-03-26",
            "capabilities": {},
            "clientInfo": {"name": "test-client", "version": "0.1"},
        },
    )
    print("  server:", res.get("result", {}).get("serverInfo"))
    call("notifications/initialized", None, sid)  # required notification

    print("→ tools/list")
    res, _ = call("tools/list", {}, sid)
    tools = [t["name"] for t in res["result"]["tools"]]
    print("  tools:", tools)
    expected = {"create_thread", "post_comment", "reply_comment", "list_threads",
                "get_thread", "set_status", "list_comments_since"}
    missing = expected - set(tools)
    assert not missing, f"MISSING tools: {missing}"
    print("  all 7 tools present ✓")

    print("→ create_thread")
    res, _ = call("tools/call", {
        "name": "create_thread",
        "arguments": {"title": "TEST: 三方 review 验证", "context": "auto-generated by test_client"},
    }, sid)
    out = res["result"]["content"][0]["text"]
    print(" ", out)
    tid = int(out.split("#")[1].split(":")[0])

    print("→ post_comment (claude)")
    res, _ = call("tools/call", {
        "name": "post_comment",
        "arguments": {"thread_id": tid, "author": "claude", "body": "第一个评论：这里有个问题",
                       "file": "auth.py", "line": 42, "severity": "major"},
    }, sid)
    out = res["result"]["content"][0]["text"]
    print(" ", out)
    cid = int(out.split("#")[1].split(" ")[0])

    print("→ reply_comment (zcode)")
    res, _ = call("tools/call", {
        "name": "reply_comment",
        "arguments": {"comment_id": cid, "author": "zcode", "body": "同意，已修复"},
    }, sid)
    print(" ", res["result"]["content"][0]["text"])

    print("→ post_comment (trae)")
    res, _ = call("tools/call", {
        "name": "post_comment",
        "arguments": {"thread_id": tid, "author": "trae", "body": "补充：需要加测试"},
    }, sid)
    print(" ", res["result"]["content"][0]["text"])

    print("→ get_thread (verify tree)")
    res, _ = call("tools/call", {"name": "get_thread", "arguments": {"thread_id": tid}}, sid)
    print(res["result"]["content"][0]["text"])
    assert "reply to" not in res["result"]["content"][0]["text"], "reply nesting may be off"

    print("→ set_status")
    res, _ = call("tools/call", {
        "name": "set_status",
        "arguments": {"thread_id": tid, "status": "resolved", "author": "claude"},
    }, sid)
    print(" ", res["result"]["content"][0]["text"])

    print("→ list_comments_since (24h)")
    res, _ = call("tools/call", {
        "name": "list_comments_since", "arguments": {"since": "24h"},
    }, sid)
    print(res["result"]["content"][0]["text"])

    print("\n✅ ALL TOOL CALLS SUCCEEDED over real MCP protocol.")


if __name__ == "__main__":
    main()
